name = "MazeGeneration"
uuid = "660427cc-5121-4683-8d58-d563c5dc56d4"
authors = ["kenneth77716 <kennethkenneth762@gmail.com>"]
version = "0.1.0"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
